List<String> dogBreedList =["Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "French Bulldog",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "Siberian Husky",
  "Dachshund",
  "Doberman Pinscher",
  "Shih Tzu",
  "Great Dane",
  "Boxer",
  "Shetland Sheepdog",
  "Pug",
  "Chihuahua",
  "Border Collie",
  "Australian Shepherd",
  "Yorkshire Terrier",
  "Cocker Spaniel",
  "Shiba Inu",
  "Havanese",
  "Maltese",
  "Bichon Frise",
  "Cavalier King Charles Spaniel",
  "Akita",
  "Samoyed",
  "Shetland Sheepdog",
  "Pomeranian",
  "Bernese Mountain Dog",
  "Basset Hound",
  "Irish Wolfhound",
  "Scottish Terrier",
  "Afghan Hound",
  "Borzoi",
  "Bloodhound",
  "Dalmatian",
  "Collie",
  "Newfoundland",
  "Rhodesian Ridgeback",
  "Basenji",
  "Papillon",
  "Brussels Griffon",
  "Scottish Deerhound",
  "Alaskan Malamute",
  "Chinese Shar-Pei",
  "Whippet",
  "Chinese Crested",
  "American Eskimo Dog",
  "Old English Sheepdog",
  "Portuguese Water Dog",
  "Bullmastiff",
  "Tibetan Mastiff",
  "Neapolitan Mastiff",
  "Briard",
  "Bergamasco",
  "Irish Setter",
  "English Setter",
  "Gordon Setter",
  "Weimaraner",
  "Vizsla",
  "Flat-Coated Retriever",
  "Nova Scotia Duck Tolling Retriever",
  "Welsh Corgi",
  "Miniature Schnauzer",
  "Giant Schnauzer",
  "Standard Schnauzer",
  "Japanese Chin",
  "Brussels Griffon",
  "Pekingese",
  "Australian Terrier",
  "Cairn Terrier",
  "West Highland White Terrier",
  "Lhasa Apso",
  "Tibetan Terrier",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Irish Terrier",
  "Bedlington Terrier",
  "Kerry Blue Terrier",
  "Soft Coated Wheaten Terrier",
  "Scottish Terrier",
  "Australian Terrier",
  "Silky Terrier",
  "Toy Fox Terrier",
  "Manchester Terrier",
  "English Toy Spaniel",
  "Tibetan Spaniel",
  "Japanese Chin",
  "Chow Chow",
  "Keeshond",
  "Dalmatian",
  "Great Pyrenees",
  "Saint Bernard",
  "Leonberger"];

  List<String> catBreedList = [
  "Abyssinian",
  "American Shorthair",
  "Balinese",
  "Bengal",
  "Birman",
  "British Shorthair",
  "Burmese",
  "Chartreux",
  "Cornish Rex",
  "Devon Rex",
  "Egyptian Mau",
  "Exotic Shorthair",
  "Himalayan",
  "Japanese Bobtail",
  "Maine Coon",
  "Manx",
  "Norwegian Forest",
  "Oriental Shorthair",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Somali",
  "Sphynx",
  "Tonkinese",
  "Turkish Angora",
  "Turkish Van",
];
List<String> fishBreedList = [
  "Angelfish",
  "Betta",
  "Cichlid",
  "Clownfish",
  "Discus",
  "Guppy",
  "Goldfish",
  "Koi",
  "Molly",
  "Neon Tetra",
  "Oscar",
  "Platy",
  "Plecostomus",
  "Rainbowfish",
  "Rasbora",
  "Tetra",
  "Barb",
  "Danio",
  "Loach",
  "Catfish",
  "Gourami",
  "Killifish",
  "Pufferfish",
  "Shrimp",
  "Snail",
  "Swordtail",
  "Tang",
  "Wrasse",
  "Zebrafish",
];
List<String> symptomsList = [
    "Coughing",
    "Sneezing",
    "Lethargy",
    "Loss of Appetite",
    "Vomiting",
    "Diarrhea",
    "Fever",
    "Excessive Thirst",
    "Excessive Panting",
    "Difficulty Breathing",
    "Limping",
    "Excessive Drooling",
    "Blood in Urine",
    "Blood in Stool",
    "Swollen Joints",
    "Excessive Scratching",
    "Skin Rash",
    "Jaundice",
    "Weakness",
    "Collapse",
  ];